### ISSUE TITLE
Transfer to conda-forge

### ISSUE THREAD

**Issue by johnwason** [pyri-project-conda/general_robotics_toolbox-feedstock#2]
@wolfv @traversaro @Tobias-Fischer

This feedstock is ready to transfer to conda-forge

**Comment by Tobias-Fischer** [comment]
Awesome. Are you happy to create a pull request?

**Comment by johnwason** [comment]
Can I transfer the repo to conda-forge organization and then modify it once there to use the standard build tools?

**Comment by johnwason** [comment]
Oh, nevermind I will create a pull request to `staged-recipes`

**Comment by wolfv** [comment]
yes, that's the way to go :)

**Comment by johnwason** [comment]
All set: https://github.com/conda-forge/staged-recipes/pull/22741
